from sqlalchemy import Column, String, Text, DateTime, ForeignKey, JSON, Enum
from sqlalchemy.orm import relationship
from datetime import datetime
import enum

from app.models.database import Base


class SummaryType(str, enum.Enum):
    """Enum for summary types"""
    GENERAL = "general"
    BUG = "bug"
    UX = "ux"
    FEATURE = "feature"


class Summary(Base):
    """Model for storing summaries generated by Gemini"""
    __tablename__ = "summaries"

    id = Column(String(36), primary_key=True)
    transcription_id = Column(String(36), ForeignKey("transcriptions.id"), nullable=False)
    status = Column(String(20), nullable=False, default="pending")  # pending, processing, completed, failed
    summary_type = Column(Enum(SummaryType), nullable=False, default=SummaryType.GENERAL)
    format = Column(String(20), nullable=False, default="markdown")  # markdown, json
    content = Column(JSON, nullable=True)
    error_message = Column(Text, nullable=True)
    session_id = Column(String(36), nullable=True)
    created_at = Column(DateTime, nullable=False, default=datetime.utcnow)
    completed_at = Column(DateTime, nullable=True)

    # Relationships
    transcription = relationship("Transcription", back_populates="summaries")
    tickets = relationship("Ticket", back_populates="summary", foreign_keys="Ticket.summary_id")

    def __repr__(self):
        return f"<Summary(id='{self.id}', type='{self.summary_type}', status='{self.status}')>"